# Generated by Django 6.0.7 on 2026-08-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
