# Generated by Django 6.0.7 on 2026-08-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_store', '0002_alter_category_table_alter_customer_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
